import type { LearningContent } from '@/lib/types';
import { geminiVideoExplanation } from '@/lib/gemini';
import { generateConceptualDiagram } from '@/lib/groq';
import { generateLessonVideo } from '@/lib/stability';
import { generateVeoVideo } from '@/lib/veo';

/** Minimal valid Mermaid 10 flowchart so the diagram never breaks. Used when Groq diagram fails or key is missing. */
function getMinimalDiagram(topic: string): string {
  const label = topic.length > 40 ? topic.substring(0, 37) + '...' : topic;
  const safe = label.replace(/"/g, "'").trim() || 'Topic';
  return `flowchart TD\n  A["${safe}"] --> B["Overview"]`;
}

/** True if the string looks like valid Mermaid flowchart code. */
function isValidMermaidDiagram(code: string): boolean {
  const t = code.trim();
  return t.length > 10 && /flowchart\s+(TD|LR|BT|RL)/i.test(t) && /-->|--/.test(t);
}

/**
 * Enrich content with: video script from Gemini, conceptual diagram from Groq.
 * Diagram is generated by Groq (generateConceptualDiagram) and explains the whole process and all steps.
 * If Groq diagram fails or GROQ_API_KEY is missing, use a minimal safe diagram.
 */
export async function enrichWithGemini(content: LearningContent): Promise<LearningContent> {
  const hasGemini = Boolean(process.env.GEMINI_API_KEY?.trim());
  const hasGroq = Boolean(process.env.GROQ_API_KEY?.trim());
  const topic = content.topic;
  const result = { ...content };

  const videoScriptPromise = hasGemini
    ? geminiVideoExplanation(topic, {
        explanation: content.explanation,
        breakdown: content.breakdown,
      })
    : Promise.resolve(null);
  const diagramPromise = hasGroq
    ? generateConceptualDiagram(content)
    : Promise.resolve(null);

  const [videoScriptSettled, diagramSettled] = await Promise.all([
    videoScriptPromise.then((v) => v).catch(() => null),
    diagramPromise.then((d) => d).catch((e) => {
      console.warn('Groq conceptual diagram failed:', e instanceof Error ? e.message : e);
      return null;
    }),
  ]);

  if (videoScriptSettled?.trim()) {
    result.videoScript = videoScriptSettled.trim();
  }

  const rawDiagram = diagramSettled?.trim() ?? '';
  result.diagramCode =
    rawDiagram && isValidMermaidDiagram(rawDiagram) ? rawDiagram : getMinimalDiagram(topic);

  return result;
}

/**
 * Enrich content with lesson visuals: run Stability AI and Veo 3 (Gemini) in parallel.
 * - Stability: keyframe image + optional MP4 (hosted video API often unavailable).
 * - Veo 3: MP4 via Gemini API.
 * Prefer Stability image and video when available; if Stability does not produce video,
 * display Veo 3 output. Uses Stability keyframe image when we have it.
 */
export async function enrichWithStability(content: LearningContent): Promise<LearningContent> {
  const hasStability = Boolean(process.env.STABILITY_API_KEY?.trim());
  const hasVeo = Boolean(process.env.GEMINI_API_KEY?.trim());
  if (!hasStability && !hasVeo) {
    return content;
  }

  const stabilityPromise = hasStability
    ? generateLessonVideo(content, { tryVideo: true }).then((r) => ({ imageDataUrl: r.imageDataUrl, videoDataUrl: r.videoDataUrl }))
    : Promise.resolve(null);
  const veoPromise = hasVeo ? generateVeoVideo(content) : Promise.resolve(null);

  const [stabilitySettled, veoSettled] = await Promise.all([
    stabilityPromise.then((r) => r).catch((e) => {
      console.warn('Stability video generation failed:', e instanceof Error ? e.message : e);
      return null;
    }),
    veoPromise,
  ]);

  const stability = stabilitySettled ?? null;
  const veo = veoSettled ?? null;

  const videoImageDataUrl = stability?.imageDataUrl;
  const videoDataUrl = stability?.videoDataUrl ?? veo?.videoDataUrl ?? undefined;

  if (!videoImageDataUrl && !videoDataUrl) {
    return content;
  }

  return {
    ...content,
    ...(videoImageDataUrl && { videoImageDataUrl }),
    ...(videoDataUrl && { videoDataUrl }),
  };
}
